AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tw-route-alarms

  Sample SAM Template for tw-route-alarms

Globals:
  Function:
    Timeout: 300

Parameters:
  AlarmNotificationTopicInfo:
    Description: SNS Topic ARN for sending INFO notifications
    Type: 'String'
    Default: 'arn:aws:sns:ap-southeast-2:978697126183:AlarmNotificationTopic'
  AlarmNotificationTopicCritical:
    Description: SNS Topic ARN for sending CRITICAL notifications
    Type: 'String'
    Default: 'arn:aws:sns:ap-southeast-2:978697126183:AlarmNotificationTopic'
  McczTgwRouteTableIdProd:
    Description: Transit Gateway route table Id for Prod
    Type: 'String'
    Default: 'tgw-rtb-0b9f6576353fd370f'
  McczTgwRouteTableIdNonProd:
    Description: Transit Gateway route table Id for NonProd
    Type: 'String'
    Default: 'tgw-rtb-11111111111111111'
  TgwRtRoutesCountFunctionName:
    Description: Name of the TgwRtRoutesCountFunction lambda
    Type: 'String'
    Default: 'tgw-route-tbl-routes-count-function'
  McczTgwNewVpcRouteCWAlarmFunctionName:
    Description: Name of the McczTgwNewVpcRouteCWAlarmFunction lambda
    Type: 'String'
    Default: 'mccz-tgw-new-vpc-routes-notification'

Resources:
  ###########################################################################
  #  DynamoDB
  ###########################################################################
  McczVpcRoutesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'McczVpcRoutesTable'
      AttributeDefinitions:
        - AttributeName: 'HashKey'
          AttributeType: 'S'
        - AttributeName: 'SortKey'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'HashKey'
          KeyType: 'HASH'
        - AttributeName: 'SortKey'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      
  ###########################################################################
  #  Lambda
  ###########################################################################
  TgwRtRoutesCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref TgwRtRoutesCountFunctionName
      CodeUri: src/
      Handler: tgw_rt_routes_count.lambda_handler
      Runtime: python3.7
      Role: !GetAtt TgwRtRoutesCountFunctionRole.Arn
      Architectures:
        - x86_64
      Events:
        CloudWatchSource:
          Type: Schedule
          Properties:
            # Runs every 5 minutes
            Schedule: 'cron(0/5 * * * ? *)'
      Environment:
        Variables:
          LOG_LEVEL: 'INFO'
          MCCZ_TGW_ROUTE_TABLE_ID_PROD: !Ref McczTgwRouteTableIdProd
          MCCZ_TGW_ROUTE_TABLE_ID_NONPROD: !Ref McczTgwRouteTableIdNonProd
          CW_METRIC_NAMESPACE: 'ato'
          CW_METRIC_PROD: 'tgw_route_tbl_routes_count_prod'
          CW_METRIC_NONPROD: 'tgw_route_tbl_routes_count_nonprod'

  McczTgwNewVpcRouteCWAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref McczTgwNewVpcRouteCWAlarmFunctionName
      CodeUri: src/
      Handler: mccz_tgw_new_vpc_routes_notification.lambda_handler
      Runtime: python3.7
      Role: !GetAtt McczTgwNewVpcRouteCWAlarmFunctionRole.Arn
      Architectures:
        - x86_64
      Events:
        CloudWatchSource:
          Type: Schedule
          Properties:
            # Runs every 5 minutes
            Schedule: 'cron(0/5 * * * ? *)'
      Environment:
        Variables:
          LOG_LEVEL: 'INFO'
          MCCZ_TGW_ROUTE_TABLE_ID_PROD: !Ref McczTgwRouteTableIdProd
          MCCZ_TGW_ROUTE_TABLE_ID_NONPROD: !Ref McczTgwRouteTableIdNonProd
          TABLE_MCCZ_VPC_ROUTES: !Ref McczVpcRoutesTable
          SNS_TOPIC_ARN: !Ref AlarmNotificationTopicCritical

  ###########################################################################
  #  Cloudwatch LogGroup for lambda
  ###########################################################################
  TgwRtRoutesCountFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${TgwRtRoutesCountFunctionName}'
      RetentionInDays: 7

  McczTgwNewVpcRouteCWAlarmFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${McczTgwNewVpcRouteCWAlarmFunctionName}'
      RetentionInDays: 7

  ###########################################################################
  #  IAM Role
  ###########################################################################
  TgwRtRoutesCountFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ato-role-baseline-lambda-${TgwRtRoutesCountFunctionName}
      Path: '/service-role/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: !Sub ato-policy-baseline-lambda-${TgwRtRoutesCountFunctionName}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'cloudwatch:PutMetricData'
                Resource: '*'
              - Effect: 'Allow'
                Action:
                  - 'ec2:SearchTransitGatewayRoutes'
                Resource: '*'

  McczTgwNewVpcRouteCWAlarmFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ato-role-baseline-lambda-${McczTgwNewVpcRouteCWAlarmFunctionName}
      Path: '/service-role/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: !Sub ato-policy-baseline-lambda-${McczTgwNewVpcRouteCWAlarmFunctionName}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'sns:Publish'
                Resource:
                  - !Ref AlarmNotificationTopicCritical
              - Effect: 'Allow'
                Action:
                  - 'dynamodb:Query*'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:DeleteItem'
                Resource:
                  - !GetAtt McczVpcRoutesTable.Arn
  
  ###########################################################################
  #  Cloudwatch Alarms
  ###########################################################################
  TgwRouteTblRoutesCountProdAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: TgwRouteTblRoutesCountProdAlarm
      AlarmDescription: Alarms when VPN Propagated route count of the Prod Transit Gateway Route Table breaches the thresold
      AlarmActions:
        - !Ref AlarmNotificationTopicInfo
      OKActions:
        - !Ref AlarmNotificationTopicInfo
      MetricName: 'tgw_route_tbl_routes_count_prod'
      Namespace: 'ato'
      Dimensions: 
        - Name: 'tgw_route_table_id'
          Value: !Ref McczTgwRouteTableIdProd
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: '1'
      Period: '300'
      Statistic: Sum
      Threshold: '800'
      TreatMissingData: notBreaching

  TgwRouteTblRoutesCountNonProdAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: TgwRouteTblRoutesCountNonProdAlarm
      AlarmDescription: Alarms when VPN Propagated route count of the NonProd Transit Gateway Route Table breaches the thresold
      AlarmActions:
        - !Ref AlarmNotificationTopicInfo
      OKActions:
        - !Ref AlarmNotificationTopicInfo
      MetricName: 'tgw_route_tbl_routes_count_nonprod'
      Namespace: 'ato'
      Dimensions: 
        - Name: 'tgw_route_table_id'
          Value: !Ref McczTgwRouteTableIdNonProd
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: '1'
      Period: '300'
      Statistic: Sum
      Threshold: '800'
      TreatMissingData: notBreaching

  
